services:
  webapp:
    image: "${DOCKER_REGISTRY:-}webapp"
    build:
      context: WebApp
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"

  db_postgres:
    image: "postgres:17.2"
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
